2019-11-11 10:59:25,510 - root - INFO - db_calls.py:200 - Obtaining registry data...
2019-11-11 10:59:25,510 - root - INFO - db_calls.py:64 - Connecting to database...
2019-11-11 10:59:26,028 - root - INFO - db_calls.py:279 - Importing data...
2019-11-11 10:59:26,182 - root - ERROR - runfile.py:45 - Uncaught exception: [Errno 2] File b'/Users/davidmellor/Code/Spend_Network/Data_Projects/Project_Cascade/Regions/UK_entities/Data_Inputs/Raw_Data/source_data.csv' does not exist: b'/Users/davidmellor/Code/Spend_Network/Data_Projects/Project_Cascade/Regions/UK_entities/Data_Inputs/Raw_Data/source_data.csv'
NoneType: None
